### ISSUE TITLE
[Enhancement] Provider의 이용현황 구현

### ISSUE THREAD

**Issue by WOOSIEUN** [AUTOINVEN/autoinven#115]
## 목적
Provider 계정 접속시 Buyer가 결제한 건을 각 창고별로 확인할 수 있음

## 원하는 방향
Provider 계정 접속시 Buyer가 결제한 건을 각 창고 별 상세보기에서 내역 확인이 가능함.
Buyer의 정보를 확인할 수 있으며 과거 내역 또한 확인가능하도록 구현.

## 추가적인 내용

**Comment by abcworld123** [comment]
Provider - My Warehouse - Buy Request Lists에 if문을 ejs에서 처리함
