### ISSUE TITLE
[Bug] footer 페이지 최하단 고정

### ISSUE THREAD

**Issue by JooEuns** [AUTOINVEN/autoinven#152]
## 증상
content 내용이 페이지를 초과하는 경우 footer와 닿는 현상 발생

## 재현법
Buyer의 search warehouse 페이지에서, 사용자가 상하로 긴 창고 사진을 첨부할 경우 content 내용이 footer와 겹쳐진다

## 예상 응답
content 내용이 길어지더라도 항상 footer는 화면 최하단에 고정되도록 한다

**Comment by dpdms2148** [comment]
IoT중에서 monitoring페이지에서도 해당 현상 발생함
