### ISSUE TITLE
[Enhancement] 전반적인 UI수정

### ISSUE THREAD

**Issue by dpdms2148** [AUTOINVEN/autoinven#234]
## 목적
사용자 편의에 맞춘 UI수정

## 원하는 방향
- [ ] 테이블 헤더가 두 줄이 되는 곳 한 줄로 보이도록 수정 (용어 변경)
- [ ] 전반적으로 테이블 헤더에서 사용하는 용어와 순서를 통일
- [ ] 메뉴와 페이지에서 사용되는 이름을 통일
- [ ] 버튼 hover 관련 수정

## 추가적인 내용
#219 #220 #221 이 모두 Close 되고, 해당 브랜치가 Merge 된 다음 시작해주세요.

**Comment by WOOSIEUN** [comment]
@dpdms2148 @JooEuns 시작하셔도 괜찮아요
