### ISSUE TITLE
[Bug] 창고 등록 불가 오류

### ISSUE THREAD

**Issue by JooEuns** [AUTOINVEN/autoinven#280]
## 증상
Search Warehouse 에서 창고 신청시 error 발생

## 재현법
Buyer의 Search Warehouse에서 창고 신청시 error 발생하는 현상

## 예상 응답
정상적으로 창고 신청 완료

**Comment by WOOSIEUN** [comment]
autoinven |   code: 'ER_BAD_FIELD_ERROR',
autoinven |   errno: 1054,
autoinven |   sqlMessage: "Unknown column 'NaN' in 'field list'",
autoinven |   sqlState: '42S22',
autoinven |   index: 0,
autoinven |   sql: "INSERT INTO RequestForBuy SET `reqDate` = '2021-08-24 06:46:32.592', `reqType` = 'ReqByBuyer', `buyerID` = 'testBuyer', `warehouseID` = NaN, `area` = 3, `startDate` = '2021-08-24', `endDate` = '2021-08-26', `amount` = 'NaN'"
autoinven | }
